default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  variables:
    sql_mode: TRADITIONAL

development:
  <<: *default
  database: ticketing_system
  username: root
  password: 7vals

test:
  <<: *default
  database: ticketing_system_test
  username: root
  password: 7vals